### PR TITLE
Create confidential Patient example

### PR DESCRIPTION
**Pull request by tmsMedcom**
#19 
Added a Patient example, which includes a patient with confidential name and address.

### CODE REVIEW

**Comment by jvitrifork** [comment]
@tmsMedcom I would prefer if the name and address was actually a name and an address. The point with the security tag is to flag that the information may actually be present, but that it should be treated confidential.

**Comment by jvitrifork** [comment]
That was the intent

**Comment by tmsMedcom** [comment]
@jvitrifork I see your point - I have changed it so the patient has a name and an address, as it was intended.

**Comment by jvitrifork** [comment]
@tmsMedcom https://github.com/hl7dk/dk-core/pull/40/files#diff-6afb0a5834d2d9777ca375cf6ac13177e2c4e443c60c9da3a1839095fb14952bR8 says 'retricted'

**Pull request merged**
