### PR TITLE
V.2.0.0

### PR DESCRIPTION
**Pull request by tmsMedcom**
Updated DKCore in accordance to the HL7-Dk meeting on Monday. Issue #61, #62 (#31) and #63 has been handled.

### CODE REVIEW

**Review by jkiddo — APPROVED** [review]

**Comment by Kirstinerosenbeck** [comment]
I have reviewed all changes and compared to the meeting minutes from September 5th. Everything is as expected.

**Comment by jkiddo** [comment]
@Kirstinerosenbeck / @tmsMedcom  Final publication is not done yet but you can see an early example on https://hl7.dk/fhir/core/2.0.0/

**Comment by tmsMedcom** [comment]
Can I distribute the link (https://hl7.dk/fhir/core/2.0.0/) to the HL7-DK? Or do you prefer I wait until final publication?

Med Venlig Hilsen

Thea Mentz Sørensen
Konsulent
MedCom, Forskerparken 10, 5230 Odense M
Kontor: (+45) 65 43 20 30 Mobil: (+45) 29 62 02 90
***@***.******@***.***>, medcom.dk<https://www.medcom.dk/>
***@***.***

Fra: Jens Kristian Villadsen ***@***.***>
Sendt: 7. september 2022 10:18
Til: hl7dk/dk-core ***@***.***>
Cc: Thea Mentz Sørensen ***@***.***>; Mention ***@***.***>
Emne: Re: [hl7dk/dk-core] V.2.0.0 (PR #64)


@Kirstinerosenbeck<https://github.com/Kirstinerosenbeck> / @tmsMedcom<https://github.com/tmsMedcom> Final publication is not done yet but you can see an early example on https://hl7.dk/fhir/core/2.0.0/

**Comment by jkiddo** [comment]
As long as it is only distributed for review in mind, I'm fine with that - but the publication is not yet finalized.

**Comment by jkiddo** [comment]
@tmsMedcom the publication is now ready to be finalized.

**Pull request merged**
